In [1]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('titanic.csv')[['Age', 'Pclass', 'Fare', 'Survived']]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [5]:
df.isnull().mean()

Age         0.198653
Pclass      0.000000
Fare        0.000000
Survived    0.000000
dtype: float64

<h3 style='color:blue'>Train-Test Split</h3>

In [8]:
X = df.drop(columns='Survived')
y = df['Survived']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
X_train.shape, X_test.shape

((712, 3), (179, 3))

In [9]:
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

<h3 style='color:blue'>Importing KNN Imputer</h3>

In [11]:
# Select the number K ( K nearest neighbours)
# Calculate nan_euclidian_distances
# Find the mean of the K Nearest Neighbors 

###   nan_euclidian_distances   ###
# dist(x,y) = sqrt(weight * sq. distance from present coordinates)
        # where:  weight = Total # of coordinates / # of present coordinates
# For example, the distance between [3, na, na, 6] and [1, na, 4, 5] is:    sqrt(4/2*[(3-1)^2 + (6-5)^2])     (for 2nd no. missing val in row 1)
#                                                                                     square dist. of that columns only in which both have some value.

In [12]:
from sklearn.impute import KNNImputer 
knn = KNNImputer() 

X_train_tnf = knn.fit_transform(X_train)
X_test_tnf = knn.transform(X_test)

In [14]:
pd.DataFrame(X_train_tnf, columns=X_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  39.0     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]

In [16]:
from sklearn.linear_model import LogisticRegression 
lr = LogisticRegression() 

lr.fit(X_train_tnf, y_train)
y_pred = lr.predict(X_test_tnf)

from sklearn.metrics import accuracy_score 
accuracy_score(y_pred, y_test)

0.7430167597765364

<h3 style='color:blue'>Changing K-neighbours Value</h3>

In [27]:
knn = KNNImputer(n_neighbors=1)       # Number of neighboring samples to use for imputation.

X_train_tnf = knn.fit_transform(X_train)
X_test_tnf = knn.transform(X_test)

lr = LogisticRegression() 

lr.fit(X_train_tnf, y_train)
y_pred = lr.predict(X_test_tnf)

accuracy_score(y_pred, y_test)

0.7318435754189944

<h3 style='color:blue'>weight parameter of KNNImputer </h3>

In [ ]:
# weights{‘uniform’, ‘distance’} or callable, default=’uniform’
        # Weight function used in prediction. Possible values:

# ‘uniform’ : uniform weights. All points in each neighborhood are weighted equally.
# ‘distance’ : weight points by the inverse of their distance. in this case, 
                        # closer neighbors of a query point will have a greater influence than neighbors which are further away.

# for k=2,         uniform =    v1 + v2                 distance =             v1 / d1 + v2 / d2           d1, d2 -> dist. from that point
#                              ---------                                     ---------------------         v1, v2 -> values present in that cell
#                                  2                                                    2

In [38]:
knn = KNNImputer(n_neighbors=5, weights='distance')    

X_train_tnf = knn.fit_transform(X_train)
X_test_tnf = knn.transform(X_test)

lr = LogisticRegression() 

lr.fit(X_train_tnf, y_train)
y_pred = lr.predict(X_test_tnf)

accuracy_score(y_pred, y_test)

0.7374301675977654

<h3 style='color:blue'>Comparison with SimpleImputer (mean) </h3>

In [37]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()

X_train_tnf = si.fit_transform(X_train)
X_test_tnf = si.transform(X_test)

lr = LogisticRegression() 

lr.fit(X_train_tnf, y_train)
y_pred2 = lr.predict(X_test_tnf)

accuracy_score(y_pred2, y_test)

0.7374301675977654