<h1 style="color:red">Fetching data from an API</h1>

In [1]:
# API = Application Programming Interface
# API ia a messenger and a set of rules that allows two different software programs to talk to, 
#  share data with, and interact with each other without human intervention.

In [2]:
# Making a GET Request :
###   response = requests.get(url)   ###

# requests	Library
# get()	    HTTP method (asking for data)
# url	    Address of the API
# response	Server’s reply

In [3]:
import pandas as pd
import requests         # python library,it helps python to talk with websites or APIs

<h2 style="color:brown">Reading API data (json) </h2>

<p><b>Public Cat API</b></p>

In [4]:
response = requests.get('https://api.thecatapi.com/v1/images/search?limit=10')  
# response : This response contains everything the server sent back, including:
# Status code (success or failure)
# Headers (metadata)
# Actual data (body)

# Status Code
###   response.status_code   ###
# Common status codes:
# 200 ->	Success 
# 400 ->	Bad request
# 401 ->	Unauthorized 
# 404 ->	Not found
# 500 ->	Server error

In [5]:
data = response.json()               #  returns data in json format   ## in this case it's a list of python dictionaries(key-value pairs)
print(type(data))                    # prints the type of data -> "list"
print(type(data[0]["url"]))            # prints the type of data["url"] -> str
print(data[0].keys())                   # keys of the dict data[0],  in data -> list of dictionaries,
# display(data)                # it will display data in json format

df = pd.DataFrame(response.json())   #  converting json format into pandas dataframe
print(type(df))
display(df)                          #  displays Entire DataFrame
# display(df.head())                 #  First 5 rows (by default)
# display(df.head(10))               #  First 10 rows

<class 'list'>
<class 'str'>
dict_keys(['id', 'url', 'width', 'height'])
<class 'pandas.core.frame.DataFrame'>

           id                                               url  width  height
0          ku          https://cdn2.thecatapi.com/images/ku.jpg    900     794
1          lm          https://cdn2.thecatapi.com/images/lm.jpg    560     420
2         3jq         https://cdn2.thecatapi.com/images/3jq.jpg   4928    3264
3         44j         https://cdn2.thecatapi.com/images/44j.jpg    500     333
4         4s4         https://cdn2.thecatapi.com/images/4s4.jpg    500     332
5         7d9         https://cdn2.thecatapi.com/images/7d9.jpg    500     332
6         b5r         https://cdn2.thecatapi.com/images/b5r.jpg    640     960
7         bbc         https://cdn2.thecatapi.com/images/bbc.png    400     295
8         ehd         https://cdn2.thecatapi.com/images/ehd.jpg    675     449
9  MjA2ODQ4OQ  https://cdn2.thecatapi.com/images/MjA2ODQ4OQ.jpg    604     377

<h2 style="color:brown">Get Books</h2>

<p><b>FreeAPI</b></p>

In [6]:
response2 = requests.get("https://api.freeapi.app/api/v1/public/books")
print(response2.status_code)
# display(response2.json())


df2 = pd.DataFrame([response2.json()])          
# it may Fails because the root JSON is a single dictionary (not a list), so Pandas doesn't know how to split it into rows. so pass it inside []
display(df2)
df2 = pd.DataFrame(response2.json()["data"])   #  Peels one layer, access the list of dict data stored in the "data" of the key-value pair of root JSON
display(df2) 

df2 = pd.DataFrame(response2.json()["data"]["data"])  # peels 2nd layer, access the list of dist "data" of the 1st layer "data"
display(df2)

200

,statusCode,data,message,success
0,200,"{'page': 1, 'limit': 10, 'totalPages': 21, 'pr...",Books fetched successfully,True

,page,limit,totalPages,previousPage,nextPage,totalItems,currentPageItems,data
0,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 1, 'etag': 'Kfk..."
1,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 2, 'etag': 'aT6..."
2,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 3, 'etag': '6NO..."
3,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 4, 'etag': 'M+a..."
4,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 5, 'etag': 'b7y..."
5,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 6, 'etag': 'N/l..."
6,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 7, 'etag': 'Nky..."
7,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 8, 'etag': '3bP..."
8,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 9, 'etag': '48w..."
9,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 10, 'etag': 'sQ..."

,kind,id,etag,selfLink,volumeInfo,saleInfo,accessInfo,searchInfo
0,books#volume,1,KfkbeLGcmEA,https://www.googleapis.com/books/v1/volumes/KA...,"{'title': 'Practices of an Agile Developer', '...","{'country': 'IN', 'saleability': 'FOR_SALE', '...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...","{'textSnippet': 'These are the proven, effecti..."
1,books#volume,2,aT6gRM8dLto,https://www.googleapis.com/books/v1/volumes/bm...,"{'title': 'Developer Testing', 'subtitle': 'Bu...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'NO_PAGES', '...",{'textSnippet': 'The first guide to cover test...
2,books#volume,3,6NOaUBND99o,https://www.googleapis.com/books/v1/volumes/A3...,{'title': 'Java Programming for Android Develo...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'With the help of Java Program...
3,books#volume,4,M+aHgueRKtY,https://www.googleapis.com/books/v1/volumes/lT...,"{'title': 'Ask Your Developer', 'subtitle': 'H...","{'country': 'IN', 'saleability': 'FOR_SALE', '...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'How to compete in the digital...
4,books#volume,5,b7yZqHfYIlM,https://www.googleapis.com/books/v1/volumes/lA...,{'title': 'AWS Certified Developer Official St...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This Sybex Study Guide covers...
5,books#volume,6,N/lZcdU/jzU,https://www.googleapis.com/books/v1/volumes/UF...,"{'title': 'Android Development Patterns', 'sub...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': '“A must read for all develope...
6,books#volume,7,NkycvzZAzfU,https://www.googleapis.com/books/v1/volumes/ox...,"{'title': 'HTTP Developer's Handbook', 'author...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'The HTTP Developer&#39;s Hand...
7,books#volume,8,3bPp8sgWsAk,https://www.googleapis.com/books/v1/volumes/ld...,"{'title': 'Mastering ENVY/Developer', 'authors...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This book covers VisualAge fo...
8,books#volume,9,48wn8Io+xX0,https://www.googleapis.com/books/v1/volumes/df...,"{'title': 'Coder to Developer', 'subtitle': 'T...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'NO_PAGES', '...","{'textSnippet': 'Inside, you&#39;ll find plent..."
9,books#volume,10,sQCa8UyT7gM,https://www.googleapis.com/books/v1/volumes/zp...,{'title': 'A Day at Work with a Software Devel...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This book is sure to grab the...

<h3>Accessing only some specific Columns</h3>

In [7]:
df2 = pd.DataFrame(response2.json()["data"]["data"])[['id', "etag", "selfLink", "volumeInfo"]]   # if we want only specific columns from the dataframe
# pass the column names inside double square brackets [[-----]]
df2

,id,etag,selfLink,volumeInfo
0,1,KfkbeLGcmEA,https://www.googleapis.com/books/v1/volumes/KA...,"{'title': 'Practices of an Agile Developer', '..."
1,2,aT6gRM8dLto,https://www.googleapis.com/books/v1/volumes/bm...,"{'title': 'Developer Testing', 'subtitle': 'Bu..."
2,3,6NOaUBND99o,https://www.googleapis.com/books/v1/volumes/A3...,{'title': 'Java Programming for Android Develo...
3,4,M+aHgueRKtY,https://www.googleapis.com/books/v1/volumes/lT...,"{'title': 'Ask Your Developer', 'subtitle': 'H..."
4,5,b7yZqHfYIlM,https://www.googleapis.com/books/v1/volumes/lA...,{'title': 'AWS Certified Developer Official St...
5,6,N/lZcdU/jzU,https://www.googleapis.com/books/v1/volumes/UF...,"{'title': 'Android Development Patterns', 'sub..."
6,7,NkycvzZAzfU,https://www.googleapis.com/books/v1/volumes/ox...,"{'title': 'HTTP Developer's Handbook', 'author..."
7,8,3bPp8sgWsAk,https://www.googleapis.com/books/v1/volumes/ld...,"{'title': 'Mastering ENVY/Developer', 'authors..."
8,9,48wn8Io+xX0,https://www.googleapis.com/books/v1/volumes/df...,"{'title': 'Coder to Developer', 'subtitle': 'T..."
9,10,sQCa8UyT7gM,https://www.googleapis.com/books/v1/volumes/zp...,{'title': 'A Day at Work with a Software Devel...

<h2 style="color:brown">Fetching a City Weather </h2>

<p><b>OpenWeather forecast API</b></p>

In [8]:
# he two string formatting methods is mixed.
# The URL uses %(CITY)s style formatting, but the string is written as an f-string (f""), so the variables are not substituted.
# Also, the API parameter names are incorrect in params (CITY, API_KEY). The API expects q and appid. 
#  ❌❌❌❌❌❌❌❌❌❌❌❌❌❌

API_KEY = "955976b11d772a8e251a7bc80c033dae"  
CITY = "DELHI"
url = f"http://api.openweathermap.org/data/2.5/weather?q=%(CITY)s&appid=%(API_KEY)s&units=metric"

response = requests.get(url, params={'CITY':CITY, "API_KEY":API_KEY})
response.status_code     # error 401❌❌

401

In [9]:
API_KEY = "955976b11d772a8e251a7bc80c033dae"  
CITY = "DELHI"
url = f"http://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric"

# FETCH DATA
response = requests.get(url)
df3 = pd.DataFrame([response.json()])
display(df3)

if response.status_code == 200:
    data = response.json()
    temp = data['main']['temp']
    weather = data['weather'][0]['description']
    print(f"The weather in {CITY} is {weather} with a temperature of {temp}°C.")
    # print("The weather in %(city)s with a temperature of is %(temp)s°C." %{'city':name,'temp':temp})    # we can use old stlye formatting also.
else:
    print(f"Error: {response.status_code}. Check if your API Key is active!")

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 77.2167, 'lat': 28.6667}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.81, 'feels_like': 27.23, 'temp_min...",10000,"{'speed': 0.35, 'deg': 314, 'gust': 1.08}",{'all': 77},1773079345,"{'country': 'IN', 'sunrise': 1773018492, 'suns...",19800,1273294,Delhi,200

The weather in DELHI is broken clouds with a temperature of 28.81°C.

In [10]:
# Different Version (Recommended)

API_KEY = "955976b11d772a8e251a7bc80c033dae"
url = "http://api.openweathermap.org/data/2.5/weather"

cities = ["New York","London","Paris","Tokyo","Dubai","Beijing","Moscow","Berlin","Mumbai","Delhi"]
df = pd.DataFrame()
for city in cities:
    params = {
        "q": city,
        "appid": API_KEY,
        "units": "metric"
    }
    response = requests.get(url, params=params)
    data = response.json()
    df = pd.concat([ df, pd.DataFrame([data]) ], ignore_index=True)

df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': -74.006, 'lat': 40.7143}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 20.88, 'feels_like': 19.91, 'temp_min...",10000,"{'speed': 3.45, 'deg': 211, 'gust': 6.15}",{'all': 2},1773079050,"{'country': 'US', 'sunrise': 1773055057, 'suns...",-14400,5128581,New York,200
1,"{'lon': -0.1257, 'lat': 51.5085}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 10.33, 'feels_like': 9.61, 'temp_min'...",9584,"{'speed': 1.99, 'deg': 206, 'gust': 3.6}",{'all': 53},1773079406,"{'country': 'GB', 'sunrise': 1773037721, 'suns...",0,2643743,London,200
2,"{'lon': 2.3488, 'lat': 48.8534}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 13.95, 'feels_like': 12.89, 'temp_min...",10000,"{'speed': 1.64, 'deg': 171, 'gust': 2.53}",{'all': 65},1773079156,"{'country': 'FR', 'sunrise': 1773037022, 'suns...",3600,2988507,Paris,200
3,"{'lon': 139.6917, 'lat': 35.6895}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 5.45, 'feels_like': 0.93, 'temp_min':...",10000,"{'speed': 7.46, 'deg': 7, 'gust': 7.56}",{'all': 74},1773078806,"{'country': 'JP', 'sunrise': 1773090001, 'suns...",32400,1850144,Tokyo,200
4,"{'lon': 55.3047, 'lat': 25.2582}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 24.3, 'feels_like': 24.43, 'temp_min'...",10000,"{'speed': 2.16, 'deg': 287, 'gust': 2.22}",{'all': 100},1773079139,"{'country': 'AE', 'sunrise': 1773023671, 'suns...",14400,292223,Dubai,200
5,"{'lon': 116.3972, 'lat': 39.9075}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 6.09, 'feels_like': 3.19, 'temp_min':...",10000,"{'speed': 4.02, 'deg': 191, 'gust': 10.63}",{'all': 30},1773078687,"{'country': 'CN', 'sunrise': 1773095693, 'suns...",28800,1816670,Beijing,200
6,"{'lon': 37.6156, 'lat': 55.7522}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 3.61, 'feels_like': 0.43, 'temp_min':...",10000,"{'speed': 3.56, 'deg': 246, 'gust': 9.23}",{'all': 100},1773079041,"{'country': 'RU', 'sunrise': 1773028876, 'suns...",10800,524901,Moscow,200
7,"{'lon': 13.4105, 'lat': 52.5244}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 11.14, 'feels_like': 9.93, 'temp_min'...",10000,"{'speed': 2.22, 'deg': 168, 'gust': 4.13}",{'all': 56},1773079063,"{'country': 'DE', 'sunrise': 1773034521, 'suns...",3600,2950159,Berlin,200
8,"{'lon': 72.8479, 'lat': 19.0144}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 28.95, 'feels_like': 30.37, 'temp_min...",10000,"{'speed': 4.58, 'deg': 3, 'gust': 5.68}",{'all': 0},1773078998,"{'country': 'IN', 'sunrise': 1773019332, 'suns...",19800,1275339,Mumbai,200
9,"{'lon': 77.2167, 'lat': 28.6667}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.81, 'feels_like': 27.23, 'temp_min...",10000,"{'speed': 0.35, 'deg': 314, 'gust': 1.08}",{'all': 77},1773079345,"{'country': 'IN', 'sunrise': 1773018492, 'suns...",19800,1273294,Delhi,200

<h2 style="color:brown">Using For Loop </h2>

<p><b>OpenWeather forecast API</b></p>

In [11]:
API_KEY = "955976b11d772a8e251a7bc80c033dae"  
CITY = "DELHI"

URL = "https://api.openweathermap.org/data/2.5/forecast"
params = {
    "q": CITY,
    "appid": API_KEY,
    "units": "metric"
}

response = requests.get(URL, params=params)
data = response.json()
print(type(data))            # Print the type of the returned JSON object (should be dict)
print(data.keys())           # Print all top-level keys present in the JSON response

# FETCH DATA
weather_report = []    ## empty python list to store processed weather records
# display(data["list"])

for item in data["list"]:                # Loop through each forecast entry in the 'list' key
    temp = item["main"]["temp"]
    humidity = item["main"]["humidity"]
    desc = item["weather"][0]["description"]
    timestamp = item["dt_txt"]
    # Create a dictionary representing one row of weather data
    records = {"temperature":temp, "humidity":humidity, "description":desc, "timestamp":timestamp}

    weather_report.append(records)

# Convert the list of dictionaries into a Pandas DataFrame   
df4 = pd.DataFrame(weather_report)
display(df4)

<class 'dict'>
dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

    temperature  humidity       description            timestamp
0         28.81        15     broken clouds  2026-03-09 18:00:00
1         27.77        17     broken clouds  2026-03-09 21:00:00
2         25.64        19  scattered clouds  2026-03-10 00:00:00
3         26.35        19     broken clouds  2026-03-10 03:00:00
4         32.63        12     broken clouds  2026-03-10 06:00:00
5         36.33         7     broken clouds  2026-03-10 09:00:00
6         35.76         6     broken clouds  2026-03-10 12:00:00
7         32.72         9     broken clouds  2026-03-10 15:00:00
8         29.43        11     broken clouds  2026-03-10 18:00:00
9         26.79        13  scattered clouds  2026-03-10 21:00:00
10        24.80        15  scattered clouds  2026-03-11 00:00:00
11        26.95        13  scattered clouds  2026-03-11 03:00:00
12        34.51         8     broken clouds  2026-03-11 06:00:00
13        38.05         5   overcast clouds  2026-03-11 09:00:00
14        35.94         6   overcast clouds  2026-03-11 12:00:00
15        31.91         8   overcast clouds  2026-03-11 15:00:00
16        29.16         8   overcast clouds  2026-03-11 18:00:00
17        26.72         8     broken clouds  2026-03-11 21:00:00
18        24.86         8   overcast clouds  2026-03-12 00:00:00
19        26.79         7   overcast clouds  2026-03-12 03:00:00
20        33.51         5   overcast clouds  2026-03-12 06:00:00
21        37.73         5     broken clouds  2026-03-12 09:00:00
22        36.49         7     broken clouds  2026-03-12 12:00:00
23        32.46        11         clear sky  2026-03-12 15:00:00
24        30.42        12         clear sky  2026-03-12 18:00:00
25        27.60        15  scattered clouds  2026-03-12 21:00:00
26        25.10        17        few clouds  2026-03-13 00:00:00
27        27.75        16         clear sky  2026-03-13 03:00:00
28        34.50        13         clear sky  2026-03-13 06:00:00
29        37.22         9        few clouds  2026-03-13 09:00:00
30        36.60         8        few clouds  2026-03-13 12:00:00
31        32.10        11     broken clouds  2026-03-13 15:00:00
32        29.87        12     broken clouds  2026-03-13 18:00:00
33        27.81        14   overcast clouds  2026-03-13 21:00:00
34        25.77        14   overcast clouds  2026-03-14 00:00:00
35        27.05        12   overcast clouds  2026-03-14 03:00:00
36        33.94         9   overcast clouds  2026-03-14 06:00:00
37        36.93         7   overcast clouds  2026-03-14 09:00:00
38        35.75         7   overcast clouds  2026-03-14 12:00:00
39        32.17         9   overcast clouds  2026-03-14 15:00:00

<p><b>jsonplaceholder API</b></p>

In [15]:
df5 = pd.DataFrame()  ## empty dataFrame

# Loop through pages 1 to 10 (JSONPlaceholder supports pagination)
for page in range(1,11):
    url = "https://jsonplaceholder.typicode.com/posts"
    params = {"page":page, "_limit":100 }

    response = requests.get(url, params=params)
    temp_df = pd.DataFrame(response.json())
    
    # Concatenate the new page DataFrame with the main DataFrame
    # ignore_index=True resets the index so it remains continuous (0, 1, 2, ...)
    df5 = pd.concat([temp_df, df5], ignore_index=True)    

print(df5.shape)
display(df5)


# pandas removed .append() Because this pattern is very inefficient:
# bcz It Copies the entire DataFrame every loop
# Is extremely slow and Wastes memory

# So pandas forced best practices.  -->   replacement:   pd.concat()

(1000, 4)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
995,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
996,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
997,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
998,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
999,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

<h2 style="color:brown">Convert DataFrame into CSV </h2>

In [13]:
df5.to_csv("user_details.csv")
df4.to_csv("weather_report@DELHI.csv")

<h2 style="color:brown">Dataframe with images instead of url</h2>

In [14]:
from IPython.display import HTML, display

url = "https://api.thecatapi.com/v1/images/search?limit=10"
response = requests.get(url)

df = pd.DataFrame(response.json())
display(df)

df["url"] = df["url"].apply(
    lambda x: f'<img src="{x}" width="100"/>'
)

display(HTML(df.to_html(escape=False)))

           id                                               url  width  height
0         291         https://cdn2.thecatapi.com/images/291.jpg   2032    1520
1         3ju         https://cdn2.thecatapi.com/images/3ju.jpg    500     375
2         48a         https://cdn2.thecatapi.com/images/48a.gif    475     266
3         51j         https://cdn2.thecatapi.com/images/51j.jpg    880     760
4         air         https://cdn2.thecatapi.com/images/air.jpg    427     640
5         bqv         https://cdn2.thecatapi.com/images/bqv.jpg   1000     667
6         c47         https://cdn2.thecatapi.com/images/c47.jpg   2592    1936
7         ckf         https://cdn2.thecatapi.com/images/ckf.jpg   1600    1200
8         djf         https://cdn2.thecatapi.com/images/djf.jpg    449     600
9  MTYyNzY0Ng  https://cdn2.thecatapi.com/images/MTYyNzY0Ng.jpg    768    1024