<h1 style="color:red">Fetching data from an API</h1>

In [19]:
# API = Application Programming Interface
# API ia a messenger and a set of rules that allows two different software programs to talk to, 
#  share data with, and interact with each other without human intervention.

In [20]:
# Making a GET Request :
###   response = requests.get(url)   ###

# requests	Library
# get()	    HTTP method (asking for data)
# url	    Address of the API
# response	Server’s reply

In [19]:
import pandas as pd
import requests         # python library,it helps python to talk with websites or APIs

<h2 style="color:brown">Reading API data (json) </h2>

<p><b>Public Cat API</b></p>

In [5]:
response = requests.get('https://api.thecatapi.com/v1/images/search?limit=10')  
# response : This response contains everything the server sent back, including:
# Status code (success or failure)
# Headers (metadata)
# Actual data (body)

# Status Code
###   response.status_code   ###
# Common status codes:
# 200 ->	Success 
# 400 ->	Bad request
# 401 ->	Unauthorized 
# 404 ->	Not found
# 500 ->	Server error

In [7]:
data = response.json()               #  returns data in json format   ## in this case it's a list of python dictionaries(key-value pairs)
print(type(data))                    # prints the type of data -> "list"
print(type(data[0]["url"]))            # prints the type of data["url"] -> str
print(data[0].keys())                   # keys of the dict data[0],  in data -> list of dictionaries,
# display(data)                # it will display data in json format

df = pd.DataFrame(response.json())   #  converting json format into pandas dataframe
print(type(df))
display(df)                          #  displays Entire DataFrame
# display(df.head())                 #  First 5 rows (by default)
# display(df.head(10))               #  First 10 rows

<class 'list'>
<class 'str'>
dict_keys(['id', 'url', 'width', 'height'])
<class 'pandas.core.frame.DataFrame'>

           id                                               url  width  height
0         6u4         https://cdn2.thecatapi.com/images/6u4.jpg   1024     683
1         a1a         https://cdn2.thecatapi.com/images/a1a.jpg    450     600
2         ahq         https://cdn2.thecatapi.com/images/ahq.jpg    500     335
3         apj         https://cdn2.thecatapi.com/images/apj.jpg    612     612
4         b1s         https://cdn2.thecatapi.com/images/b1s.jpg    900     696
5         bgp         https://cdn2.thecatapi.com/images/bgp.jpg    500     388
6         chj         https://cdn2.thecatapi.com/images/chj.jpg    620     457
7         dbj         https://cdn2.thecatapi.com/images/dbj.jpg    500     334
8  MTY0NjA3Mg  https://cdn2.thecatapi.com/images/MTY0NjA3Mg.jpg    640     425
9   N8bl5RjPG   https://cdn2.thecatapi.com/images/N8bl5RjPG.jpg   2560    1707

<h2 style="color:brown">Get Books</h2>

<p><b>FreeAPI</b></p>

In [69]:
response2 = requests.get("https://api.freeapi.app/api/v1/public/books")
print(response2.status_code)
# display(response2.json())


df2 = pd.DataFrame([response2.json()])          
# it may Fails because the root JSON is a single dictionary (not a list), so Pandas doesn't know how to split it into rows. so pass it inside []
display(df2)
df2 = pd.DataFrame(response2.json()["data"])   #  Peels one layer, access the list of dict data stored in the "data" of the key-value pair of root JSON
display(df2) 

df2 = pd.DataFrame(response2.json()["data"]["data"])  # peels 2nd layer, access the list of dist "data" of the 1st layer "data"
display(df2)

200

,statusCode,data,message,success
0,200,"{'page': 1, 'limit': 10, 'totalPages': 21, 'pr...",Books fetched successfully,True

,page,limit,totalPages,previousPage,nextPage,totalItems,currentPageItems,data
0,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 1, 'etag': 'Kfk..."
1,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 2, 'etag': 'aT6..."
2,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 3, 'etag': '6NO..."
3,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 4, 'etag': 'M+a..."
4,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 5, 'etag': 'b7y..."
5,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 6, 'etag': 'N/l..."
6,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 7, 'etag': 'Nky..."
7,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 8, 'etag': '3bP..."
8,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 9, 'etag': '48w..."
9,1,10,21,False,True,210,10,"{'kind': 'books#volume', 'id': 10, 'etag': 'sQ..."

,kind,id,etag,selfLink,volumeInfo,saleInfo,accessInfo,searchInfo
0,books#volume,1,KfkbeLGcmEA,https://www.googleapis.com/books/v1/volumes/KA...,"{'title': 'Practices of an Agile Developer', '...","{'country': 'IN', 'saleability': 'FOR_SALE', '...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...","{'textSnippet': 'These are the proven, effecti..."
1,books#volume,2,aT6gRM8dLto,https://www.googleapis.com/books/v1/volumes/bm...,"{'title': 'Developer Testing', 'subtitle': 'Bu...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'NO_PAGES', '...",{'textSnippet': 'The first guide to cover test...
2,books#volume,3,6NOaUBND99o,https://www.googleapis.com/books/v1/volumes/A3...,{'title': 'Java Programming for Android Develo...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'With the help of Java Program...
3,books#volume,4,M+aHgueRKtY,https://www.googleapis.com/books/v1/volumes/lT...,"{'title': 'Ask Your Developer', 'subtitle': 'H...","{'country': 'IN', 'saleability': 'FOR_SALE', '...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'How to compete in the digital...
4,books#volume,5,b7yZqHfYIlM,https://www.googleapis.com/books/v1/volumes/lA...,{'title': 'AWS Certified Developer Official St...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This Sybex Study Guide covers...
5,books#volume,6,N/lZcdU/jzU,https://www.googleapis.com/books/v1/volumes/UF...,"{'title': 'Android Development Patterns', 'sub...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': '“A must read for all develope...
6,books#volume,7,NkycvzZAzfU,https://www.googleapis.com/books/v1/volumes/ox...,"{'title': 'HTTP Developer's Handbook', 'author...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'The HTTP Developer&#39;s Hand...
7,books#volume,8,3bPp8sgWsAk,https://www.googleapis.com/books/v1/volumes/ld...,"{'title': 'Mastering ENVY/Developer', 'authors...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This book covers VisualAge fo...
8,books#volume,9,48wn8Io+xX0,https://www.googleapis.com/books/v1/volumes/df...,"{'title': 'Coder to Developer', 'subtitle': 'T...","{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'NO_PAGES', '...","{'textSnippet': 'Inside, you&#39;ll find plent..."
9,books#volume,10,sQCa8UyT7gM,https://www.googleapis.com/books/v1/volumes/zp...,{'title': 'A Day at Work with a Software Devel...,"{'country': 'IN', 'saleability': 'NOT_FOR_SALE...","{'country': 'IN', 'viewability': 'PARTIAL', 'e...",{'textSnippet': 'This book is sure to grab the...

<h3>Accessing only some specific Columns</h3>

In [83]:
df2 = pd.DataFrame(response2.json()["data"]["data"])[['id', "etag", "selfLink", "volumeInfo"]]   # if we want only specific columns from the dataframe
# pass the column names inside double square brackets [[-----]]
df2

,id,etag,selfLink,volumeInfo
0,1,KfkbeLGcmEA,https://www.googleapis.com/books/v1/volumes/KA...,"{'title': 'Practices of an Agile Developer', '..."
1,2,aT6gRM8dLto,https://www.googleapis.com/books/v1/volumes/bm...,"{'title': 'Developer Testing', 'subtitle': 'Bu..."
2,3,6NOaUBND99o,https://www.googleapis.com/books/v1/volumes/A3...,{'title': 'Java Programming for Android Develo...
3,4,M+aHgueRKtY,https://www.googleapis.com/books/v1/volumes/lT...,"{'title': 'Ask Your Developer', 'subtitle': 'H..."
4,5,b7yZqHfYIlM,https://www.googleapis.com/books/v1/volumes/lA...,{'title': 'AWS Certified Developer Official St...
5,6,N/lZcdU/jzU,https://www.googleapis.com/books/v1/volumes/UF...,"{'title': 'Android Development Patterns', 'sub..."
6,7,NkycvzZAzfU,https://www.googleapis.com/books/v1/volumes/ox...,"{'title': 'HTTP Developer's Handbook', 'author..."
7,8,3bPp8sgWsAk,https://www.googleapis.com/books/v1/volumes/ld...,"{'title': 'Mastering ENVY/Developer', 'authors..."
8,9,48wn8Io+xX0,https://www.googleapis.com/books/v1/volumes/df...,"{'title': 'Coder to Developer', 'subtitle': 'T..."
9,10,sQCa8UyT7gM,https://www.googleapis.com/books/v1/volumes/zp...,{'title': 'A Day at Work with a Software Devel...

<h2 style="color:brown">Fetching a City Weather </h2>

<p><b>OpenWeather forecast API</b></p>

In [84]:
API_KEY = "955976b11d772a8e251a7bc80c033dae"  
CITY = "DELHI"
url = f"http://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric"

# FETCH DATA
response = requests.get(url)
df3 = pd.DataFrame([response.json()])
display(df3)

if response.status_code == 200:
    data = response.json()
    temp = data['main']['temp']
    weather = data['weather'][0]['description']
    print(f"The weather in {CITY} is {weather} with a temperature of {temp}°C.")
else:
    print(f"Error: {response.status_code}. Check if your API Key is active!")

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 77.2167, 'lat': 28.6667}","[{'id': 741, 'main': 'Fog', 'description': 'fo...",stations,"{'temp': 10.05, 'feels_like': 9.72, 'temp_min'...",100,"{'speed': 0, 'deg': 0}",{'all': 100},1767031531,"{'type': 1, 'id': 9165, 'country': 'IN', 'sunr...",19800,1273294,Delhi,200

The weather in DELHI is fog with a temperature of 10.05°C.

<h2 style="color:brown">Using For Loop </h2>

<p><b>OpenWeather forecast API</b></p>

In [23]:
API_KEY = "955976b11d772a8e251a7bc80c033dae"  
CITY = "DELHI"

URL = "https://api.openweathermap.org/data/2.5/forecast"
params = {
    "q": CITY,
    "appid": API_KEY,
    "units": "metric"
}

response = requests.get(URL, params=params)
data = response.json()
print(type(data))            # Print the type of the returned JSON object (should be dict)
print(data.keys())           # Print all top-level keys present in the JSON response

# FETCH DATA
weather_report = []    ## empty python list to store processed weather records
# display(data["list"])

for item in data["list"]:                # Loop through each forecast entry in the 'list' key
    temp = item["main"]["temp"]
    humidity = item["main"]["humidity"]
    desc = item["weather"][0]["description"]
    timestamp = item["dt_txt"]
    # Create a dictionary representing one row of weather data
    records = {"temperature":temp, "humidity":humidity, "description":desc, "timestamp":timestamp}

    weather_report.append(records)

# Convert the list of dictionaries into a Pandas DataFrame   
df4 = pd.DataFrame(weather_report)
display(df4)

<class 'dict'>
dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

    temperature  humidity       description            timestamp
0         13.05        82        few clouds  2025-12-30 15:00:00
1         14.47        63        few clouds  2025-12-30 18:00:00
2         15.20        44         clear sky  2025-12-30 21:00:00
3         15.19        28         clear sky  2025-12-31 00:00:00
4         15.73        26         clear sky  2025-12-31 03:00:00
5         20.69        19         clear sky  2025-12-31 06:00:00
6         23.23        15   overcast clouds  2025-12-31 09:00:00
7         21.70        16   overcast clouds  2025-12-31 12:00:00
8         19.60        19     broken clouds  2025-12-31 15:00:00
9         17.89        24  scattered clouds  2025-12-31 18:00:00
10        16.58        31         clear sky  2025-12-31 21:00:00
11        15.47        34         clear sky  2026-01-01 00:00:00
12        15.71        34        few clouds  2026-01-01 03:00:00
13        20.40        26  scattered clouds  2026-01-01 06:00:00
14        23.00        23   overcast clouds  2026-01-01 09:00:00
15        21.79        26   overcast clouds  2026-01-01 12:00:00
16        20.30        28   overcast clouds  2026-01-01 15:00:00
17        18.09        33     broken clouds  2026-01-01 18:00:00
18        16.37        42  scattered clouds  2026-01-01 21:00:00
19        15.26        47        few clouds  2026-01-02 00:00:00
20        15.61        38         clear sky  2026-01-02 03:00:00
21        20.12        27         clear sky  2026-01-02 06:00:00
22        22.73        25         clear sky  2026-01-02 09:00:00
23        21.28        29         clear sky  2026-01-02 12:00:00
24        18.77        36         clear sky  2026-01-02 15:00:00
25        17.08        39         clear sky  2026-01-02 18:00:00
26        15.79        42         clear sky  2026-01-02 21:00:00
27        14.75        46         clear sky  2026-01-03 00:00:00
28        14.90        45         clear sky  2026-01-03 03:00:00
29        19.58        34         clear sky  2026-01-03 06:00:00
30        22.31        25         clear sky  2026-01-03 09:00:00
31        20.91        29         clear sky  2026-01-03 12:00:00
32        18.53        35         clear sky  2026-01-03 15:00:00
33        16.68        39         clear sky  2026-01-03 18:00:00
34        15.27        42         clear sky  2026-01-03 21:00:00
35        14.27        43         clear sky  2026-01-04 00:00:00
36        14.30        43         clear sky  2026-01-04 03:00:00
37        19.11        30         clear sky  2026-01-04 06:00:00
38        22.32        23         clear sky  2026-01-04 09:00:00
39        20.86        25         clear sky  2026-01-04 12:00:00

<p><b>jsonplaceholder API</b></p>

In [16]:
df5 = pd.DataFrame()  ## empty dataFrame

# Loop through pages 1 to 10 (JSONPlaceholder supports pagination)
for page in range(1,11):
    url = "https://jsonplaceholder.typicode.com/posts"
    params = {"page":page, "_limit":100 }

    data = requests.get(url, params=params)
    temp_df = pd.DataFrame(data.json())
    
    # Concatenate the new page DataFrame with the main DataFrame
    # ignore_index=True resets the index so it remains continuous (0, 1, 2, ...)
    df5 = pd.concat([temp_df, df5], ignore_index=True)    

print(df5.shape)
display(df5)


# pandas removed .append() Because this pattern is very inefficient:
# bcz It Copies the entire DataFrame every loop
# Is extremely slow and Wastes memory

# So pandas forced best practices.  -->   replacement:   pd.concat()

(1000, 4)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
995,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
996,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
997,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
998,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
999,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

<h2 style="color:brown">Convert DataFrame into CSV </h2>

In [17]:
df5.to_csv("user_details.csv")
df4.to_csv("weather_report@DELHI.csv")

<h2 style="color:brown">Dataframe with images instead of url</h2>

In [79]:
from IPython.display import HTML, display

url = "https://api.thecatapi.com/v1/images/search?limit=10"
response = requests.get(url)

df = pd.DataFrame(response.json())
display(df)

df["url"] = df["url"].apply(
    lambda x: f'<img src="{x}" width="100"/>'
)

display(HTML(df.to_html(escape=False)))

           id                                               url  width  height
0          68          https://cdn2.thecatapi.com/images/68.jpg    500     386
1         1v5         https://cdn2.thecatapi.com/images/1v5.jpg    500     335
2         6j7         https://cdn2.thecatapi.com/images/6j7.jpg    500     332
3         6lh         https://cdn2.thecatapi.com/images/6lh.jpg    500     335
4         a9d         https://cdn2.thecatapi.com/images/a9d.jpg    800    1065
5         aka         https://cdn2.thecatapi.com/images/aka.gif    400     224
6         cdq         https://cdn2.thecatapi.com/images/cdq.png    500     346
7         djl         https://cdn2.thecatapi.com/images/djl.jpg    500     351
8         dtp         https://cdn2.thecatapi.com/images/dtp.jpg    640     480
9  MTk5NTYyNw  https://cdn2.thecatapi.com/images/MTk5NTYyNw.jpg    900     953